apiVersion: v1
kind: Service
metadata:
  name: rebom-backend-service
  namespace: rebom
  labels:
    app: rebom
spec:
  selector:
    app: rebom
    name: rebom-backend
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000