apiVersion: v1
kind: Service
metadata:
  name: rebom-postgres
  namespace: rebom
  labels:
    app: rebom
spec:
  selector:
    app: rebom
    name: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432